[package]
name = "audio_rodio"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "audio_rodio"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rodio = "0.19.0"
rustler = "0.34.0"
